### ISSUE TITLE
Any chance of a 3.0.0 version to go with scala-xml 2.0.0-RC1

### ISSUE THREAD

**Issue by DavidGoodenough** [andyglow/scala-xml-diff#11]
I understand that 3.0.0 will be released tomorrow, any chance of an upgrade?

**Comment by andyglow** [comment]
hello, @DavidGoodenough 
3.0.0-RC3 is already there. not released, but code has been prepared
https://github.com/andyglow/scala-xml-diff/pull/12

will release once scala 3.0.0 is officially out

**Comment by DavidGoodenough** [comment]
Excellent, thank you

**Comment by DavidGoodenough** [comment]
Seems to be out along with scala-xml 2.0.0

**Comment by andyglow** [comment]
`scala-xml-diff 3.0.0` has just been released with scala3 support. 
please check. 
will be available for download from maven central in next couple of hours.
