### ISSUE TITLE
Scalatest a compile-time dependency for 2.0.2

### ISSUE THREAD

**Issue by adamosloizou** [andyglow/scala-xml-diff#4]
Hello,

Thank you for writing this library, it's quite useful.
I have recently realised some dependency issues with scalatest in my build.
This is because `scala-xml-diff` is bringing in `scalatest` at compile time.

Would you be able to have it at test time?

Thanks

**Comment by hosamaly** [comment]
This issue should be fixed in PR #3, which has been merged already. We just need a new release.

**Comment by hosamaly** [comment]
Version 2.0.3 declares Scalatest as a `provided` library. That should fix this issue.
